# Generated by Django 4.2.1 on 2023-06-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('piece', models.CharField(max_length=100)),
                ('emplacement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('contenu', models.TextField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.capteur')),
            ],
        ),
    ]
