# Generated by Django 4.2.1 on 2023-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0002_alter_donnee_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
