# Generated by Django 4.2.1 on 2023-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0003_alter_capteur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnee',
            name='contenu',
        ),
        migrations.AddField(
            model_name='donnee',
            name='nombre_individus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donnee',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
